apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: dimito
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - dimito.ir
    - dimito.io
    secretName: frontend-tls
  rules:
  - host: dimito.ir
    http:
      paths:
      - path: /fa
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /en
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /
        pathType: Exact
        backend:
          service:
            name: frontend
            port:
              number: 3000
  - host: dimito.io
    http:
      paths:
      - path: /fa
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /en
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /
        pathType: Exact
        backend:
          service:
            name: frontend
            port:
              number: 3000